### ISSUE TITLE
64bit edge weight?

### ISSUE THREAD

**Issue by mpetri** [KaHIP/KaMinPar#1]
I ran into this problem when working with a graph with large edge weights:

```
[metrics.cc:34][edge_cut] Assertion failed: `0 <= cut && cut <= std::numeric_limits<EdgeWeight>::max()`
cut=12500155258
[metrics.cc:34][edge_cut] Assertion failed: `0 <= cut && cut <= std::numeric_limits<EdgeWeight>::max()`
cut=12625870524
```

I tried changing the definition of `EdgeWeight` to `int64_t` but that throws all sorts of compile errors. Is something like this supported?

**Comment by DanielSeemaier** [comment]
Hi, I have just added a CMake option for 64 bit edge weights `-DKAMINPAR_64BIT_EDGE_WEIGHTS=On`

**Comment by mpetri** [comment]
Thanks!
