### ISSUE TITLE
Massive graph support

### ISSUE THREAD

**Issue by zbj2008cn** [KaHIP/KaMinPar#10]
Hello, I m trying to use KaMinPar to do some graph partition works but the size of Graph is very large, 90,000,000 nodes and 95,000,000 edges and want to partition it into 100000 parts. Does KaMinPar support this graph size? Thanks

**Comment by DanielSeemaier** [comment]
Hey! Sure, partitioning graphs of that size should be reasonable fast.

**Comment by zbj2008cn** [comment]
@DanielSeemaier Thanks! I will try it now.

**Comment by zbj2008cn** [comment]
Hello, I tried KaMinPar on my massive graph with 84379625 nodes and 9960386906 edges. 

There are some wrongs like due to big edge num over integer:

Number of edges:       2740904628  ./KaMinPar/kaminpar-common/asserting_cast.h: In function 'To kaminpar::asserting_case(From) [with To = int; From = unsigned int]':
./KaMinPar/kaminpar-common/asserting_cast.h:54: FAILED ASSERTION
            in_range<To>value
with expansion:
            false
2740904628 of type j not in range of type i
Aborted (core dumped)

**Comment by DanielSeemaier** [comment]
Hey, you can fix these issues by using 64 bit edge IDs and weights via the CMake flags

```
-DKAMINPAR_64BIT_EDGE_IDS=On -DKAMINPAR_64BIT_WEIGHTS=On
```

**Comment by zbj2008cn** [comment]
Thanks! It works now and unbelievable fast！

**Comment by zbj2008cn** [comment]
Toplevel:
 Number of nodes: 84379625 | Number of edges: 19920773812
  Running refinement on 65536 blocks
   1. Greedy Balancer
   2. Label Propagation
  Extending partition from 65536 blocks to 131072 blocks
  Running refinement on 131072 blocks
   1. Greedy Balancer
   2. Label Propagation

############################################################# Result Summary ###
Global Timer: ................................... 668.890 s    
|- Read input graph: ............................ 316.651 s    
|- Partitioning: ................................ 352.150 s    
|  |- Rearrange by degree-buckets: .............. 8.615 s      
|  |  |- Sort nodes by degree bucket: ........... 0.124 s      
|  |  |- Rearrange input graph: ................. 8.354 s      
|  |  `- Deallocation: .......................... 0.073 s      
|  |- Remove isolated nodes: .................... 0.019 s      
|  |- Refinement: ............................... 60.206 s  (8)
|  |  |- Allocation: ............................ 0.000 s      
|  |  |- Greedy Balancer: ....................... 12.865 s  (7)
|  |  `- Label Propagation: ..................... 47.340 s  (7)
|  |- Coarsening: ............................... 172.283 s (6)
|  |  |- Level (0): ............................. 170.565 s    
|  |  |- Level (1): ............................. 1.593 s      
|  |  |- Level (2): ............................. 0.110 s      
|  |  |- Level (3): ............................. 0.011 s      
|  |  |- Level (4): ............................. 0.002 s      
|  |  `- Deallocation: .......................... 0.000 s      
|  |- Initial partitioning scheme: .............. 0.011 s      
|  |- Uncoarsening: ............................. 0.083 s   (5)
|  |  |- Level (5): ............................. 0.000 s      
|  |  |- Level (4): ............................. 0.000 s      
|  |  |- Level (3): ............................. 0.000 s      
|  |  |- Level (2): ............................. 0.005 s      
|  |  `- Level (1): ............................. 0.077 s      
|  |- Initial partitioning: ..................... 110.830 s (6)
|  |  |- Preprocessing: ......................... 8.516 s   (6)
|  |  |- Allocation: ............................ 0.544 s   (6)
|  |  |- Bipartitioning: ........................ 101.608 s (6)
|  |  `- Copy subgraph partitions: .............. 0.150 s   (6)
|  |- Deallocation: ............................. 0.015 s      
|  `- Re-integrate isolated nodes: .............. 0.068 s      
`- IO: .......................................... 0.048 s 


Partition summary:
  Number of blocks: 131072
  Edge cut:         4101763567
  Imbalance:        0.0496894
  Feasible:         yes

Maximum resident set size: 94463740 KiB

Amazing performance！
