### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by mpetri** [KaHIP/KaMinPar#2]
Is it possible to change the LICENSE to something less restrictive. Most other tools in this space are either MIT or APACHE. For example:

- https://github.com/KarypisLab/METIS - APACHE2.0
- https://github.com/KaHIP/KaHIP - MIT
- https://github.com/KaHIP/mt-KaHIP - MIT
- https://github.com/HPCGraphAnalysis/PuLP - BSD

**Comment by DanielSeemaier** [comment]
Hi, we will change the license to MIT with the next update.

**Comment by mpetri** [comment]
Awesome thank you! Should I leave this issue open until this happens? By update you mean "proper version release"?

**Comment by mpetri** [comment]
Not be too pushy but when can I expect the next update with the license change? I'm have built a rust wrapper around KaMinPar to publish to `crates.io` so I can use the partitioning algorithms from rust and want to specify the correct license for the dependent packages.

**Comment by DanielSeemaier** [comment]
Hey, I will try to get it done by the end of next week (it's mostly about two files that I haven't written myself, so I have to double check with the original authors).

**Comment by mpetri** [comment]
Hey, I don't want to come over as overly pushy but was wondering if there is any update on this issue.

**Comment by DanielSeemaier** [comment]
Hey, sorry, I've been a bit busy during the last few weeks. I'll get it done soon.

**Comment by DanielSeemaier** [comment]
it's MIT now

**Comment by mpetri** [comment]
Thank you!
